### ISSUE TITLE
Message: LoadError: cannot load such file -- vagrant-aws

### ISSUE THREAD

**Issue by dineshr93** [sw360/sw360vagrant#27]
Hi I am trying to install sw360 in my ubuntu 18.04 running in virtual box in windows 10 PC. It threw below error

> No previously created folder found, moving on.
> -[] Destroy old box (if created previously and script exited with failure)
> There was an error loading a Vagrantfile. The file being loaded
> and the error message are shown below. This is usually caused by
> a syntax error.
> 
> Path: /home/dinesh/osstool/sw360vagrant/generate-box/Vagrantfile
> Line number: 0
> Message: LoadError: cannot load such file -- vagrant-aws
> 

Can anyone help me to rectify this error?

I dont use aws instance do it is even required to install in my local Ubuntu running in Virtual box in win 10?

**Comment by mcjaeger** [comment]
install the AWS plugin for vagrant if you setup AWS as provider
```
$ vagrant plugin install vagrant-aws
```
