### ISSUE TITLE
Components is temporarily unavailable

### ISSUE THREAD

**Issue by dineshr93** [sw360/sw360vagrant#28]
Hi @mcjaeger 
Installed in [windows 10 deployed via vagrant](https://github.com/eclipse/sw360/wiki/Deploy-sw360-on-Windows-(with-Vagrant))

Latest commit: bd1b616
![image](https://user-images.githubusercontent.com/4498415/75537207-9b675700-5a3c-11ea-9a60-2765cdd62ae7.png)

**Comment by mcjaeger** [comment]
Hi @dineshr93 which user are you when doing this, which user is logged in?

have you tried to use users as described here?

https://github.com/sw360/sw360vagrant/wiki

(Import users)

**Comment by mcjaeger** [comment]
I think this could be the part which could be missed:

https://github.com/sw360/sw360vagrant/wiki#real-login

**Comment by dineshr93** [comment]
If we login via `setup ` user above error is thrown. But for normal user the above error vanishes
