### ISSUE TITLE
Error: request could not be processed when creating new project

### ISSUE THREAD

**Issue by dineshr93** [sw360/sw360vagrant#29]
Hi @mcjaeger 

When we try to create a new project after filling all the details we get `request could not be processed error`

![image1](https://user-images.githubusercontent.com/4498415/75537580-568ff000-5a3d-11ea-84c9-17105bb58efc.png)

Installed in [windows 10 deployed via vagrant](https://github.com/eclipse/sw360/wiki/Deploy-sw360-on-Windows-(with-Vagrant))
Latest commit: bd1b616

**Comment by mcjaeger** [comment]
Hi @dineshr93 which user are you when doing this, which user is logged in?

have you tried to use users as described here?

https://github.com/sw360/sw360vagrant/wiki

(Import users)

**Comment by mcjaeger** [comment]
I think this is the part which could be missed:

https://github.com/sw360/sw360vagrant/wiki#real-login

**Comment by dineshr93** [comment]
If we are loggin via `setup `user then it is not working. But when i login as another user it works
